formatter: markdown


content: |-
  [![Quortex][logo]](https://quortex.io)

  # terraform-aws-storage

  A terraform module for Quortex infrastructure AWS persistent storage layer.

  It provides a set of resources necessary to provision the bucket and access key on Amazon AWS.

  ![infra_diagram]

  This module is available on [Terraform Registry][registry_tf_aws-eks_storage].

  Get all our terraform modules on [Terraform Registry][registry_tf_modules] or on [Github][github_tf_modules] !

  ## Created resources

  This module creates the following resources in AWS:
  - as many buckets in Amazon S3 as defined in the configuration
  - a new user, with access to the bucket
  - the key ID and secret for this user


  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}


  ---

  ## Related Projects

  This project is part of our terraform modules to provision a Quortex infrastructure for AWS.

  Check out these related projects.

  - [terraform-aws-network][registry_tf_aws-eks_network] - A terraform module for Quortex infrastructure network layer.

  - [terraform-aws-eks-cluster][registry_tf_aws-eks_cluster] - A terraform module for Quortex infrastructure AWS cluster layer.

  - [terraform-aws-eks-load-balancer][registry_tf_aws-eks_load_balancer] - A terraform module for Quortex infrastructure AWS load balancing layer.

    [logo]: https://storage.googleapis.com/quortex-assets/logo.webp
    [infra_diagram]: https://storage.googleapis.com/quortex-assets/infra_aws_001.jpg

    [registry_tf_modules]: https://registry.terraform.io/modules/quortex
    [registry_tf_aws-eks_network]: https://registry.terraform.io/modules/quortex/network/aws
    [registry_tf_aws-eks_cluster]: https://registry.terraform.io/modules/quortex/eks-cluster/aws
    [registry_tf_aws-eks_load_balancer]: https://registry.terraform.io/modules/quortex/load-balancer/aws
    [registry_tf_aws-eks_storage]: https://registry.terraform.io/modules/quortex/storage/aws
    [github_tf_modules]: https://github.com/quortex?q=terraform-


  ## Help

  **Got a question?**

  File a GitHub [issue](https://github.com/quortex/terraform-aws-storage/issues).

sort:
  enabled: false
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
